name: hackzurich2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.13.7
  - python_abi=3.13
  - readline=8.2
  - tk=8.6.13
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - geographiclib==2.1
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.6.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pydeck==0.9.1
      - pymupdf==1.26.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
