name: hackzurich2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.13.7
  - python_abi=3.13
  - readline=8.2
  - tk=8.6.13
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - distro==1.9.0
      - geographiclib==2.1
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - jiter==0.11.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.6.0
      - numpy==2.2.6
      - openai==2.0.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pymupdf==1.26.4
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - rsa==4.9.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
